### ISSUE TITLE
Connection closed. Closed reason: CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>

### ISSUE THREAD

**Issue by martin-tomasek** [andersea/bitmex-trio-websocket#3]
Quite often I lose connection. The process runs normally but does not receive any data. 
This can only be recognized by the log: 
**Connection closed. Closed reason: CloseReason <code = 1006, name = ABNORMAL_CLOSURE, reason = None>**

Is there a way to reconnect? Without breaking the module code?

**Comment by andersea** [comment]
There is not supposed to be a way to reconnect on errors. It is intentionally designed so that on any error you must open a new connection.

The listener channels are supposed to work as async generators, generating messages for each channel. The way you are supposed to know that an error has occured, is by the listener channels closing automatically. If the the listener channels are not propagating the error by closing the generators, then this is definitely a bug.

**Comment by andersea** [comment]
I don't think listeners are notified properly on connection closure. Thanks for reporting this. I will look into a fix asap.

The gist of it is as follows:

* Either `async def _run(self):` or `async def _websocket_parser(self):` methods should close all listeners on connection closure.
* Closed listeners must exit. At the moment they just keep listening for new messages.
* It may be useful if closed listeners propagated the error by reraising it. Not sure about this.
* Opening a listener on a closed connection should raise an error.

**Comment by martin-tomasek** [comment]
I'm just learning python, I've been doing php for 7 years, nodejs well. I'm just one step away from giving up and moving to nodejs :)

I think I can't catch the exception because it's already caught:
websocket.py, line 133
```
         Except ConnectionClosed as cle:
             log.info ('Connection closed. Closed reason:% s', cle.reason)
```

I was not sure if there is no other way. I can comment it out and catch it where I need it, but that's not a good way to interfere with a module that is developing.
Thank you for your work. I'm not so good to write it myself in python yet.

**Comment by andersea** [comment]
That is indeed the problem. The fix will need to involve the steps outlined in my comment above.

**Comment by andersea** [comment]
This fix should be available in pypi shortly. Thanks for reporting this issue.

**Comment by andersea** [comment]
Builds are broken at the moment, due to a problem with the build service.
