### ISSUE TITLE
Compatible with asyncio?

### ISSUE THREAD

**Issue by monk-after-90s** [andersea/bitmex-trio-websocket#6]
Is there a way in which this module could be good compatible with asyncio?

**Comment by andersea** [comment]
Well.. It might be possible to rewrite it to use [AnyIO](https://github.com/agronholm/anyio), but it isn't really a priority for me. I think Trio is the best async library.

In my view, asyncio is atrociously bad and shouldn't be used by anyone, so a direct conversion to asyncio is completely off the table.
